# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'TTNetworking' do
    pod 'AFNetworking', '~> 3.2.1'
end
